package servicemesh

// COMMON RESPONSE STRUCTS

type ServiceMesh struct {
	// API version. The value is fixed at v1 and cannot be changed.
	APIVersion string `json:"apiVersion"`
	// API type. The value is fixed at Mesh or mesh and cannot be changed.
	Kind string `json:"kind"`
	// Basic information about the service mesh.
	Metadata MeshMetadataResponse `json:"metadata"`
	// Detailed description of the service mesh / ASM instance.
	Spec MeshSpecResponse `json:"spec"`
	// Service mesh ID. Value is automatically generated by ASM.
	Status MeshStatus `json:"status"`
}

type MeshMetadataResponse struct {
	// Service mesh name. Format: 1–63 characters,
	// lowercase letters, digits, hyphens, must start with lowercase and end with letter/digit.
	Name string `json:"name"`
	// Service mesh description. 0–255 characters, letters/digits/underscores/hyphens only.
	UID string `json:"uid"`
	// Time when the service mesh was created.
	CreationTimestamp string `json:"creationTimestamp"`
}

type MeshSpecResponse struct {
	// Service mesh type. Only "Base edition" supported.
	Type string `json:"type"`
	// Service mesh version.
	Version string `json:"version"`
	// Extensions of the service mesh.
	ExtendParams ExtendParamsResponse `json:"extendParams"`
	// Whether the mesh supports IPv6.
	IPv6Enable bool `json:"ipv6Enable"`
	// Service mesh configuration.
	Config MeshConfigResponse `json:"config"`
}

type ExtendParamsResponse struct {
	// Information about clusters in the mesh.
	Clusters []MeshClusterResponse `json:"clusters"`
}

type MeshClusterResponse struct {
	// Cluster ID. Unique and used to query the cluster.
	ClusterID string `json:"clusterID"`
}

type MeshConfigResponse struct {
	// Data plane configuration of the service mesh.
	ProxyConfig ProxyConfigResponse `json:"proxyConfig"`
	// Observability configuration of the service mesh.
	TelemetryConfig TelemetryConfigResponse `json:"telemetryConfig"`
}

type ProxyConfigResponse struct {
	// IP address ranges that will be included in outbound traffic interception.
	IncludeIPRanges string `json:"includeIPRanges"`
	// IP address ranges that will be excluded from outbound traffic interception.
	ExcludeIPRanges string `json:"excludeIPRanges"`
	// Ports that will be excluded from outbound traffic redirection.
	ExcludeOutboundPorts string `json:"excludeOutboundPorts"`
	// Ports that will be excluded for inbound traffic interception.
	ExcludeInboundPorts string `json:"excludeInboundPorts"`
	// Ports that will be included for outbound traffic interception.
	IncludeOutboundPorts string `json:"includeOutboundPorts"`
	// Ports that will be included for inbound traffic interception.
	IncludeInboundPorts string `json:"includeInboundPorts"`
}

type TelemetryConfigResponse struct {
	// Tracing configuration for reporting trace in service mesh.
	Tracing TracingResponse `json:"tracing"`
}

type TracingResponse struct {
	// Tracing sampling rate.
	RandomSamplingPercentage float64 `json:"randomSamplingPercentage"`
	// Default provider names to be used.
	DefaultProviders []string `json:"defaultProviders"`
	// List of extension providers supported (e.g., Zipkin).
	ExtensionProviders []TracingExtensionProviderResponse `json:"extensionProviders"`
}

type TracingExtensionProviderResponse struct {
	// Provider name.
	Name string `json:"name"`
	// Self-defined Zipkin configuration.
	Zipkin ZipkinTracingProviderResponse `json:"zipkin"`
}

type ZipkinTracingProviderResponse struct {
	// Service address of Zipkin.
	Service string `json:"service"`
	// Service port of Zipkin.
	Port int `json:"port"`
}

// MeshStatus (Table 29)
type MeshStatus struct {
	// Service mesh status. The options are as follows:
	// Running: The service mesh is running.
	// Creating: The service mesh is being created.
	// CreateFailed: The service mesh fails to be created.
	// Deleting: The service mesh is being deleted.
	// DeleteFailed: The service mesh fails to be deleted.
	// Upgrading: The service mesh is being upgraded.
	// UpgradeFailed: The service mesh fails to be upgraded.
	// RollingBack: The service mesh is being rolled back.
	// RollbackFailed: The service mesh fails to be rolled back.
	Phase string `json:"phase"`
	// Time when the mesh was last updated.
	UpdateTimestamp string `json:"updateTimestamp"`
}
