package management

import (
	golangsdk "github.com/opentelekomcloud/gophertelekomcloud"
	"github.com/opentelekomcloud/gophertelekomcloud/internal/build"
	"github.com/opentelekomcloud/gophertelekomcloud/internal/extract"
)

type ListOpts struct {
	// Enterprise project ID, which is the ID of a project planned based on organizations.
	// If the enterprise project function is not enabled, the value is 0.
	EnterpriseProjectID string `json:"enterprise_project_id,omitempty"`

	// Query keyword, which can be a firewall ID or part of a firewall name.
	KeyWord string `json:"key_word,omitempty"`

	// Tag list, which can be obtained by calling the API for querying tags.
	Tags []ListTags `json:"tags,omitempty"`

	// Number of records displayed on each page. The value ranges from 1 to 1024.
	Limit int `json:"limit" required:"true"`

	// Offset, which specifies the start position of the record to be returned.
	// The value must be a number no less than 0. The default value is 0.
	Offset int `json:"offset" required:"true"`
}

type ListTags struct {
	// Resource tag key.
	Key string `json:"key,omitempty"`

	// Resource tag value.
	Values []string `json:"values,omitempty"`
}

// Create function is used to create a firewall
func List(client *golangsdk.ServiceClient, opts ListOpts) ([]FirewallInstanceVO, error) {
	b, err := build.RequestBody(opts, "")
	if err != nil {
		return nil, err
	}

	// POST /v1/{project_id}/firewalls/list
	raw, err := client.Post(client.ServiceURL("firewalls", "list"), b, nil, &golangsdk.RequestOpts{
		OkCodes:     []int{200},
		MoreHeaders: map[string]string{"Content-Type": "application/json"},
	})
	if err != nil {
		return nil, err
	}

	var res FirewallInstanceListResponse
	err = extract.Into(raw.Body, &res)
	return res.Data.Records, err
}

// FirewallInstanceListResponse represents the main structure containing support options and data returned for querying the firewall list.
type FirewallInstanceListResponse struct {
	// Indicates if EPS user support is available
	UserSupportEps bool `json:"user_support_eps"`
	// Indicates if NDR (Network Detection and Response) is supported
	HasNdr bool `json:"has_ndr"`
	// Indicates if postpaid support is available
	IsSupportPostpaid bool `json:"is_support_postpaid"`
	// Indicates if the basic version is supported
	IsSupportBasicVersion bool `json:"is_support_basic_version"`
	// Indicates if buying a professional version is supported
	IsSupportBuyProfessional bool `json:"is_support_buy_professional"`
	// Contains the data returned for the firewall instance list
	Data HttpFirewallInstanceListResponseData `json:"data"`
}

// HttpFirewallInstanceListResponseData represents the detailed response data for firewall instances, including pagination, project ID, total number of firewalls, and the firewall list records.
type HttpFirewallInstanceListResponseData struct {
	// The maximum number of records to return
	Limit int `json:"limit"`
	// The offset of the first record to return
	Offset int `json:"offset"`
	// The project ID associated with the firewall instances
	ProjectID string `json:"project_id"`
	// The total number of firewall instances
	Total int `json:"total"`
	// The list of firewall instance records
	Records []FirewallInstanceVO `json:"records"`
}

// FirewallInstanceVO represents the structure of an individual firewall instance.
type FirewallInstanceVO struct {
	// Firewall instance ID, which is automatically generated by the system after a CFW instance is created.
	FwInstanceId string `json:"fw_instance_id"`
	// Resource ID, which is the same as the firewall instance ID.
	ResourceId string `json:"resource_id"`
	// Firewall creation timestamp.
	Name string `json:"name"`
	// Firewall name.
	FwInstanceName string `json:"fw_instance_name"`
	// Enterprise project ID, which is generated after the enterprise project is supported for a user.
	EnterpriseProjectId string `json:"enterprise_project_id"`
	// Cluster type: 0 (active/standby), 1 (cluster).
	// In active/standby mode, there are four nodes. Two active nodes form a cluster, and the other two are the standby of the active nodes.
	// In cluster mode, only two nodes are started to form a cluster.
	HaType int `json:"ha_type"`
	// Billing mode: 0 (yearly/monthly), 1 (pay-per-use).
	ChargeMode int `json:"charge_mode"`
	// Firewall protection type. Currently, its value can only be 0 (Internet protection).
	ServiceType int `json:"service_type"`
	// Engine type: 0 (self-developed engine), 1 (Hillstone engine), or 3 (TOPSEC engine).
	EngineType int `json:"engine_type"`
	// Firewall specifications.
	Flavor Flavor `json:"flavor"`
	// Firewall status: -1 (waiting for payment), 0 (creating), 1 (deleting), 2 (running), 3 (upgrading), 4 (deleted), 5 (frozen),
	// 6 (creation failed), 7 (deletion failed), 8 (freezing failed), 9 (being stored), 10 (storage failed), or 11 (upgrade failed).
	Status int `json:"status"`
	// Tag list, which is a JSON string converted from the tag key value map, for example, "{"key":"value"}".
	Tags string `json:"tags"`
}
