---
- project:
    merge-mode: squash-merge
    vars:
      functest_project_name: "eu-de_zuul_go"
    check:
      jobs:
        - otc-golangci-lint
        - golang-make-vet
        - golang-make-test
    check-post:
      jobs:
        - golang-make-functional
    gate:
      jobs:
        - otc-golangci-lint
        - golang-make-vet
        - golang-make-test
        - golang-make-functional
